**TASK:** import numpy

In [1]:
import numpy as np

**TASK:** define vector 'x' with three coordinates

In [3]:
x = np.array([1,2,3])

**TASK:** define (2 x 2) matrix 'A' 


In [5]:
A = np.array([[1,2],[3,4]])

**TASK:** define (2 x 2) matrix 'B'

In [6]:
B = np.array([[5,6],[7,8]])

**TASK:** check the type of 'x'

In [7]:
type(x)

numpy.ndarray

**TASK:** check the type of 'A'

In [8]:
type(A)

numpy.ndarray

**TASK:**  check the shape of 'x'


In [10]:
np.shape(x)

(3,)

**TASK:** check the type of 'A'

In [11]:
np.shape(A)

(2, 2)

**TASK:** 

In [13]:
"""
Define function 'have_same_shape' which checks if two arrays have same shape.

PARAMS:
    array_1 (numpy.ndarray) - first array
    array_2 (numpy.ndarray) - second array
RETURN:
    True - if arrays have same shape
    False - if arrays do not have same shape

Also print 'Arrays must have same shape!' when returning False
"""
def have_same_shape(array_1, array_2):
  return np.shape(array_1) == np.shape(array_2)

**TASK:** call the function 'have_same_shape' with matrix 'A' and vector 'x' as inputs

In [14]:
have_same_shape(A, x)

False

**TASK:**  call the function 'have_same_shape' with matrix 'A' and matrix 'B' as inputs

In [15]:
have_same_shape(A,B)

True

**TASK:** 

In [18]:
"""
Define function 'matrix_addition' which perform matrix addition value by value.

PARAMS:
    A (numpy.ndarray) - first array
    B (numpy.ndarray) - second array
RETURN:
    C (numpy.ndarray) - new A+B array

In this task do not consider broadcasting.
Do not forget to check arrays shapes (you can use 'have_same_shape' function defined before)

"""
def matrix_addition(A, B):
  if have_same_shape(A, B):
    C = A + B
    return C
  error_msg = "error: addition can not be executed on arrays of different shape"
  return error_msg

**TASK:** call the function 'matrix_addition' with matrix 'A' and matrix 'B' as inputs

In [21]:
matrix_addition(A, B)

array([[ 6,  8],
       [10, 12]])

**TASK:** 

In [26]:
"""
Define 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition

PARAMS:
   lst_of_arr (list) - list of numpy.ndarrays
RETURN:
    NEW_ARRAY (numpy.ndarray) - new array

Use 'matrix_addition' function defined before.
"""
def multiple_matrix_addition(arrays = [np.array(0)]):
  C = arrays[0]
  for array in arrays:
    if np.shape(array) == np.shape(C):
      C = matrix_addition(array, C)
    else:
       return "error: addition can not be executed on arrays of different shape"
  return C


array([[18, 24],
       [30, 36]])

**TASK:** call the function 'multiple_matrix_addition' with matrix [A,A,B,B,B] as input


In [28]:
multiple_matrix_addition([A,A,B,B,B])

array([[18, 24],
       [30, 36]])

**TASK:** 

In [ ]:
"""
Define function 'can_multiply' that checks if two arrays (matrices) can be multiplied

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    True - if arrays can be multiplied, also print the shape of the new array
    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'
    
"""

In [29]:
def can_multiply(array_a, array_b):
  if np.shape(array_a)[1] == np.shape(array_b)[0]:
    new_array = [np.shape(array_a)[0], np.shape(array_b)[1]]
    print(new_array)
    return True
  else:
    print('Matrices can not be multiplied')
    return False

**TASK:** call the function 'can_multiply' with matrix 'A' and 'B' as inputs

In [32]:
can_multiply(A,B)

[2, 2]


True

**TASK:**  define matrix (3 x 2) matrix C

In [33]:
C = np.array([[1,2], [3,4], [5,6]])

**TASK:**  call the function 'can_multiply' with matrix 'A' and 'C' as inputs

In [34]:
can_multiply(A,C)

Matrices can not be multiplied


False

**TASK:**  call the function 'can_multiply' with matrix 'C' and 'A' as inputs (now C,A not A,C). Do you know why is the result different?

In [36]:
can_multiply(C,A)

[3, 2]


True

**TASK:** 

In [ ]:
"""
Define function 'matrix_multiplication' that multiply two numpy.ndarrays

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    NEW_ARRAY (numpy.ndarray) - new A * B array
    
Do not forget to check if two matrices can be multiplied.

"""

In [37]:
def matrix_multiplication(array_a, array_b):
  if can_multiply(array_a, array_b):
    NEW_ARRAY = array_a.dot(array_b)
    return NEW_ARRAY
  pass

**TASK:**  call the function 'matrix_multiplication' with matrix 'C' and 'B' 


In [38]:
matrix_multiplication(C,B)

[3, 2]


array([[19, 22],
       [43, 50],
       [67, 78]])

**TASK:** call the function 'matrix_multiplication' with matrix 'A' and 'C' 

In [39]:
matrix_multiplication(A,C)

Matrices can not be multiplied
